default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :tests do
    run_tests(
      project: "HelloCI.xcodeproj",
      scheme: "HelloCI",
      device: "iPhone 16",
      clean: true,
      code_coverage: true
    )
  end
end
